### ISSUE TITLE
Voice

### ISSUE THREAD

**Issue by sarellano20** [TLabAltoh/VR_Classroom#2]
Hey how are you, I have a problem with the voice chat, I can activate the microphone but I can't hear anything, greetings

**Comment by TLabAltoh** [comment]
Sorry for the late reply. After reviewing the implementation of voice chat, we decided that the system needed to be reworked, and we have been working on revamping the system for the past two days. Please check the following points to see why voice chat is not working.

# 1. Make sure this component is enabled (it was disabled by default)


<img src="https://github.com/TLabAltoh/VR_Classroom/assets/121733943/445c76d1-fad4-4340-8e65-0d9860c97ee9" width="256"></br>


<img src="https://github.com/TLabAltoh/VR_Classroom/assets/121733943/cb36a474-bb58-4f9b-8f9d-38925ab8d596" width="512"></br>


# 2. Make sure Audio streaming is enabled in WebRTCClient (formerly WebRTCDataChannel, This is a checklist item added in this update)


<img src="https://github.com/TLabAltoh/VR_Classroom/assets/121733943/0998583e-e3ad-449b-9c11-6320ed4cfd97" width="256"></br>


<img src="https://github.com/TLabAltoh/VR_Classroom/assets/121733943/53c7b347-283c-47d5-a010-74fdb95ee863" width="512"></br>

**Comment by sarellano20** [comment]
You rockkk!!
